# Generated by Django 5.1.2 on 2024-10-16 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Folder name", max_length=255, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "folder",
                "verbose_name_plural": "folders",
                "constraints": [
                    models.UniqueConstraint(fields=("name",), name="unique_name")
                ],
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="File name", max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="filesystem.folder",
                        verbose_name="folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "file",
                "verbose_name_plural": "files",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "folder"), name="unique_name_folder"
                    )
                ],
            },
        ),
    ]
